service: lanista-workout-app

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: eu-central-1
  memorySize: 512

plugins:
  - serverless-nextjs-plugin
  - serverless-offline

custom:
  serverless-nextjs:
    staticDir: ./static
    routes:
      - src: post
        path: post/{slug}
        request:
          parameters:
            paths:
              slug: true

package:
  exclude:
    - ./**
